/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_bbw_m411_connect4_RustPlayer */

#ifndef _Included_ch_bbw_m411_connect4_RustPlayer
#define _Included_ch_bbw_m411_connect4_RustPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_bbw_m411_connect4_RustPlayer
 * Method:    rustPlay
 * Signature: (B[Lch/bbw/m411/connect4/Connect4ArenaMain/Stone;)I
 */
JNIEXPORT jint JNICALL Java_ch_bbw_m411_connect4_RustPlayer_rustPlay
  (JNIEnv *, jobject, jbyte, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
